image:
  repository: 615299732970.dkr.ecr.us-east-1.amazonaws.com
  tag: "latest"
replicaCount: 2
resources:
  requests:
    cpu: "250m"
    memory: "256Mi"
  limits:
    cpu: "500m"
    memory: "512Mi"
livenessProbe:
  httpGet:
    path: /actuator/health
    port: 8080
readinessProbe:
  httpGet:
    path: /actuator/health
    port: 8080
